### ISSUE TITLE
Bug when mining using silk touch

### ISSUE THREAD

**Issue by ghost** [Yeregorix/AutoPickup#1]
Use the silk touch to break the square and not drop the item. 

Forge: 1.12.2 2705
SpongeForge:1.12.2-2705-7.1.0-BETA-3399
AutoPickup version : 1.0.0

**Comment by Yeregorix** [comment]
It works fine for me, I've tested on exactly the same sponge version and forge version. Do you have other mods or plugins ? Check all your inventory, especially if you have tested after placing ores manually.

**Comment by ghost** [comment]
After testing, the player breaks the glass, sometimes it will disappear, and sometimes it will get

**Comment by Yeregorix** [comment]
I posed exactly 2 stacks of glass and I recovered exactly 2 stacks of glass using silk touch. Can you give me a copy of your logs using a service such as pastebin and the list of your mods/plugins ?

**Comment by ghost** [comment]
Mods (22): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Another Gym Plugin, CXLibrary, Chisels & Bits, Cloud Boots Mod, FoamFix, FoamFixCore, Iron Backpacks, Iron Chest, More Furnaces, Pixel Extras, Pixelmon, Pixelmon Trainer Commands, Pokelucky, Serene Seasons, Trainer Item

**Comment by Yeregorix** [comment]
I still can't reproduce the issue, can you make me a zip file including an minimal server setup that is affected by the issue ?
