### ISSUE TITLE
The purpose of this plugin: luxury or performance?

### ISSUE THREAD

**Issue by Shybella** [Yeregorix/AutoPickup#2]
Hey, 

I was wondering the reasoning behind the plugin, is this focused on performance or just a luxury of not waiting for blocks/xp to be picked up by the player.

**Comment by Yeregorix** [comment]
Both ! 😃 It's mainly to give to the players the luxury of not waiting for items and xp but it also slightly improves performance because it avoid the creation of item and xp entities.
