### ISSUE TITLE
Mods support and blacklist

### ISSUE THREAD

**Issue by yudshj** [Yeregorix/AutoPickup#3]
Nice plugin! But when I use lazer gun in IC2, it could not automatically pick blocks which was destroyed by lazer mining gun.

I wonder when will the version with blacklist feature release?

**Comment by Yeregorix** [comment]
Thank you! 🙂
I will think about adding a kind of blacklist to make things more configurable.
Each mod is unique, it's bit hard to add support for all existing mods. I will try to see what I can do about IC2 but I can't promise anything.
I'm a bit busy those days, I will work on your ideas as soon as I can but you will have to wait a bit.

**Comment by yudshj** [comment]
Thanks a lot!♥

**Comment by Yeregorix** [comment]
Blacklists have been added in the latest version.
About mod support, IC2 problem is way too specific to be handled correctly by this plugin for now.
